DROP TRIGGER IF EXISTS trig1personal ON personal;
DROP TRIGGER IF EXISTS trig2personal ON personal;
DROP TRIGGER IF EXISTS trig_morosidad_xtrem ON citas;
DROP TRIGGER IF EXISTS trig_eficacia_tratamiento ON tratamientos;
DROP TRIGGER IF EXISTS trig_auditoria_evolucion ON citas;

DROP VIEW IF EXISTS reporte_adherencia;
DROP VIEW IF EXISTS adherencia;
DROP VIEW IF EXISTS linaje_confianza;
DROP VIEW IF EXISTS arbol_mando;
DROP VIEW IF EXISTS historial_clinico;

DROP FUNCTION IF EXISTS addpersonal();
DROP FUNCTION IF EXISTS updpersonal();
DROP FUNCTION IF EXISTS aplicar_pago(INT);
DROP FUNCTION IF EXISTS check_morosidad();
DROP FUNCTION IF EXISTS eficacia_tratamiento();
DROP FUNCTION IF EXISTS auditoria();
DROP FUNCTION IF EXISTS clasif_adh(NUMERIC);

DROP TABLE IF EXISTS auditoria_evolucion;
DROP TABLE IF EXISTS pagos;
DROP TABLE IF EXISTS citas;
DROP TABLE IF EXISTS tratamientos;
DROP TABLE IF EXISTS pacientes;
DROP TABLE IF EXISTS personal;

CREATE TABLE personal (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    rol VARCHAR NOT NULL,
    supervisor INT REFERENCES personal,
    equipo INT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT rolvalid CHECK (
        rol IN ('Medico Senior', 'Medico Junior', 'Tecnico', 'Fisioterapeuta')
    )
);

CREATE OR REPLACE FUNCTION addpersonal()
RETURNS TRIGGER AS $$
DECLARE
    cosas VARCHAR;
    team INT;
BEGIN
    IF NEW.rol = 'Medico Senior' THEN
        NEW.supervisor = NULL;
    ELSIF NEW.rol = 'Medico Junior' THEN
        SELECT p.rol INTO cosas
        FROM personal p
        WHERE p.id = NEW.supervisor;

        IF cosas <> 'Medico Senior' OR cosas IS NULL THEN
            RAISE EXCEPTION 'BLOQUEO: Supervisor invalido ingresado'
                USING ERRCODE = 'P0001';
        END IF;
    ELSIF NEW.rol IN ('Tecnico', 'Fisioterapeuta') THEN
        SELECT p.rol, p.equipo INTO cosas, team
        FROM personal p
        WHERE p.id = NEW.supervisor;

        IF cosas NOT IN ('Medico Senior', 'Medico Junior') OR cosas IS NULL THEN
            RAISE EXCEPTION 'BLOQUEO: Supervisor invalido ingresado'
                USING ERRCODE = 'P0001';
        END IF;

        NEW.equipo = team;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig1personal
BEFORE INSERT ON personal
FOR EACH ROW
EXECUTE FUNCTION addpersonal();

CREATE OR REPLACE FUNCTION updpersonal()
RETURNS TRIGGER AS $$
DECLARE
    cosas VARCHAR;
    team INT;
BEGIN
    IF NEW.rol = 'Medico Senior' THEN
        NEW.supervisor = NULL;
    ELSIF NEW.rol = 'Medico Junior' THEN
        SELECT p.rol INTO cosas
        FROM personal p
        WHERE p.id = NEW.supervisor;

        IF cosas <> 'Medico Senior' OR cosas IS NULL THEN
            RAISE EXCEPTION 'BLOQUEO: Supervisor invalido ingresado'
                USING ERRCODE = 'P0001';
        END IF;
    ELSIF NEW.rol IN ('Tecnico', 'Fisioterapeuta') THEN
        SELECT p.rol, p.equipo INTO cosas, team
        FROM personal p
        WHERE p.id = NEW.supervisor;

        IF cosas NOT IN ('Medico Senior', 'Medico Junior') OR cosas IS NULL THEN
            RAISE EXCEPTION 'BLOQUEO: Supervisor invalido ingresado'
                USING ERRCODE = 'P0001';
        END IF;

        NEW.equipo = team;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig2personal
BEFORE UPDATE ON personal
FOR EACH ROW
EXECUTE FUNCTION updpersonal();

CREATE TABLE pacientes (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    contacto VARCHAR NOT NULL,
    referido_por INT REFERENCES pacientes ON DELETE SET NULL
);

CREATE TABLE tratamientos (
    id SERIAL PRIMARY KEY,
    paciente_id INT NOT NULL REFERENCES pacientes ON DELETE CASCADE,
    medico_id INT NOT NULL REFERENCES personal ON DELETE RESTRICT,
    diagnostico TEXT NOT NULL,
    sesiones_estimadas INT NOT NULL CHECK (sesiones_estimadas > 0),
    estado VARCHAR NOT NULL DEFAULT 'ACTIVO',
    eficacia_porcentaje NUMERIC(10, 2) DEFAULT NULL,
    CHECK (estado IN ('ACTIVO', 'FINALIZADO'))
);

CREATE TABLE citas (
    id SERIAL PRIMARY KEY,
    tratamiento_id INT NOT NULL REFERENCES tratamientos ON DELETE CASCADE,
    fecha_hora TIMESTAMP NOT NULL,
    tipo_atencion VARCHAR NOT NULL,
    monto NUMERIC(12, 2) NOT NULL CHECK (monto >= 0),
    pagado BOOL NOT NULL DEFAULT FALSE,
    asistida BOOL NOT NULL DEFAULT FALSE,
    nota_evolucion TEXT,
    personal_id INT REFERENCES personal ON DELETE SET NULL
);

CREATE TABLE pagos (
    id SERIAL PRIMARY KEY,
    tratamiento_id INT NOT NULL REFERENCES tratamientos ON DELETE CASCADE,
    cita_id INT NOT NULL REFERENCES citas ON DELETE RESTRICT,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_registro VARCHAR NOT NULL
);

CREATE TABLE auditoria_evolucion (
    id SERIAL PRIMARY KEY,
    cita_id INT NOT NULL REFERENCES citas ON DELETE CASCADE,
    nota_anterior TEXT,
    nota_nueva TEXT,
    usuario_editor VARCHAR NOT NULL,
    fecha_edicion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE VIEW historial_clinico AS
SELECT
    p.id AS paciente_id,
    p.nombre,
    t.id AS tratamiento_id,
    t.medico_id,
    t.estado,
    c.id AS cita_id,
    c.fecha_hora,
    c.asistida
FROM pacientes p
LEFT JOIN tratamientos t ON t.paciente_id = p.id
LEFT JOIN citas c ON c.tratamiento_id = t.id
ORDER BY p.id, t.id, c.fecha_hora;

CREATE OR REPLACE FUNCTION aplicar_pago(tratamientoid INT)
RETURNS TABLE (
    id_pago_registrado INT,
    cita_pagada INT,
    fecha_hora_cita TIMESTAMP,
    tipo_atencion VARCHAR,
    monto NUMERIC(12,2)
) AS $$
DECLARE
    varcita RECORD;
    varpago INT;
    usuario TEXT;
BEGIN
    SELECT c.id, c.fecha_hora, c.tipo_atencion, c.monto
    INTO varcita
    FROM citas c
    WHERE c.tratamiento_id = tratamientoid
      AND c.pagado = FALSE
    ORDER BY c.fecha_hora ASC, c.id ASC
    LIMIT 1
    FOR UPDATE OF c;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'BLOQUEO: No hay deudas a pagar'
            USING ERRCODE = 'P0001';
    END IF;

    usuario := current_setting('application_name', true);
    IF usuario IS NULL OR usuario = '' THEN
        usuario := 'desconocido';
    END IF;

    UPDATE citas
    SET pagado = TRUE
    WHERE citas.id = varcita.id;

    INSERT INTO pagos (tratamiento_id, cita_id, fecha, usuario_registro)
    VALUES (tratamientoid, varcita.id, CURRENT_TIMESTAMP, usuario)
    RETURNING pagos.id INTO varpago;

    RETURN QUERY
    SELECT
        varpago,
        varcita.id,
        varcita.fecha_hora,
        varcita.tipo_atencion,
        varcita.monto;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_morosidad()
RETURNS TRIGGER AS $$
DECLARE
    pacienteid INT;
    pendientes INT;
BEGIN
    SELECT p.id INTO pacienteid
    FROM pacientes p
    JOIN tratamientos t ON t.paciente_id = p.id
    WHERE t.id = NEW.tratamiento_id;

    IF pacienteid IS NULL THEN
        RAISE EXCEPTION 'BLOQUEO: Tratamiento indicado no existe.'
            USING ERRCODE = 'P0002';
    END IF;

    SELECT COUNT(c.id) INTO pendientes
    FROM citas c
    JOIN tratamientos t ON c.tratamiento_id = t.id
    WHERE t.paciente_id = pacienteid
      AND c.pagado = FALSE
      AND c.fecha_hora < NEW.fecha_hora;

    IF pendientes >= 2 THEN
        RAISE EXCEPTION 'BLOQUEO: El paciente tiene % citas sin pagar.', pendientes
            USING ERRCODE = 'P0003';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig_morosidad_xtrem
BEFORE INSERT ON citas
FOR EACH ROW
EXECUTE FUNCTION check_morosidad();

CREATE OR REPLACE FUNCTION eficacia_tratamiento()
RETURNS TRIGGER AS $$
DECLARE
    asistencia INT;
BEGIN
    IF NEW.estado <> OLD.estado AND NEW.estado = 'FINALIZADO' THEN
        SELECT COUNT(c.id) INTO asistencia
        FROM citas c
        WHERE c.tratamiento_id = NEW.id
          AND c.asistida IS TRUE;

        IF asistencia = 0 THEN
            NEW.eficacia_porcentaje = NULL;
        ELSE
            NEW.eficacia_porcentaje = ROUND(
                100 * NEW.sesiones_estimadas::NUMERIC / asistencia::NUMERIC,
                2
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig_eficacia_tratamiento
BEFORE UPDATE ON tratamientos
FOR EACH ROW
EXECUTE FUNCTION eficacia_tratamiento();

CREATE OR REPLACE FUNCTION auditoria()
RETURNS TRIGGER AS $$
DECLARE
    usuario TEXT;
BEGIN
    IF OLD.nota_evolucion IS DISTINCT FROM NEW.nota_evolucion THEN
        usuario := current_setting('application_name', true);
        IF usuario IS NULL OR usuario = '' THEN
            usuario := 'desconocido';
        END IF;

        INSERT INTO auditoria_evolucion (
            cita_id,
            nota_anterior,
            nota_nueva,
            usuario_editor
        )
        VALUES (
            OLD.id,
            OLD.nota_evolucion,
            NEW.nota_evolucion,
            usuario
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig_auditoria_evolucion
AFTER UPDATE OF nota_evolucion ON citas
FOR EACH ROW
EXECUTE FUNCTION auditoria();

CREATE OR REPLACE VIEW arbol_mando AS
WITH RECURSIVE arbol AS (
    SELECT
        p.id,
        p.nombre,
        p.rol,
        p.supervisor,
        p.equipo,
        0 AS nivel,
        LPAD(p.id::TEXT, 6, '0') AS ruta_orden
    FROM personal p
    WHERE p.rol = 'Medico Senior'

    UNION ALL

    SELECT
        p.id,
        p.nombre,
        p.rol,
        p.supervisor,
        p.equipo,
        a.nivel + 1,
        a.ruta_orden || '.' || LPAD(p.id::TEXT, 6, '0') AS ruta_orden
    FROM personal p
    JOIN arbol a ON p.supervisor = a.id
)
SELECT * FROM arbol;

CREATE OR REPLACE VIEW linaje_confianza AS
WITH RECURSIVE linaje AS (
    SELECT
        p.id,
        p.nombre,
        p.referido_por,
        0 AS nivel,
        p.nombre::TEXT AS cadena
    FROM pacientes p
    WHERE p.referido_por IS NULL

    UNION ALL

    SELECT
        p.id,
        p.nombre,
        p.referido_por,
        l.nivel + 1,
        l.cadena || ' -> ' || p.nombre
    FROM pacientes p
    JOIN linaje l ON p.referido_por = l.id
)
SELECT * FROM linaje;

CREATE OR REPLACE FUNCTION clasif_adh(inter NUMERIC)
RETURNS VARCHAR AS $$
BEGIN
    IF inter <= 7 THEN
        RETURN 'ALTA (Ideal)';
    ELSIF inter <= 15 THEN
        RETURN 'MEDIA (Seguimiento)';
    ELSE
        RETURN 'BAJA (Riesgo de Abandono)';
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW adherencia AS
WITH citas_paciente AS (
    SELECT
        p.id,
        p.nombre,
        t.id AS trat_id,
        c.fecha_hora,
        LAG(c.fecha_hora) OVER (
            PARTITION BY p.id
            ORDER BY c.fecha_hora
        ) AS fecha_previa
    FROM citas c
    JOIN tratamientos t ON t.id = c.tratamiento_id
    JOIN pacientes p ON t.paciente_id = p.id
)
SELECT
    id,
    nombre,
    trat_id,
    ROUND((EXTRACT(EPOCH FROM (fecha_hora - fecha_previa)) / 86400.0)::NUMERIC, 2) AS intervalo
FROM citas_paciente
WHERE fecha_previa IS NOT NULL;

CREATE OR REPLACE VIEW reporte_adherencia AS
SELECT
    id,
    nombre,
    ROUND(AVG(intervalo), 1) AS promedio_intervalo,
    clasif_adh(ROUND(AVG(intervalo), 1)) AS estado_adherencia
FROM adherencia
GROUP BY id, nombre
ORDER BY nombre;
